/* THIS FILE IS AUTOGENERATED FROM MediaTrackSupportedConstraints.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_MediaTrackSupportedConstraintsBinding_h
#define mozilla_dom_MediaTrackSupportedConstraintsBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct MediaTrackSupportedConstraintsAtoms;
struct NativePropertyHooks;
class ProtoAndIfaceCache;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

struct MediaTrackSupportedConstraints : public DictionaryBase
{
  Optional<bool> mAspectRatio;
  bool mBrowserWindow;
  bool mDeviceId;
  bool mEchoCancellation;
  bool mFacingMode;
  bool mFrameRate;
  Optional<bool> mGroupId;
  bool mHeight;
  Optional<bool> mLatency;
  bool mMediaSource;
  bool mMozAutoGainControl;
  bool mMozNoiseSuppression;
  Optional<bool> mSampleRate;
  Optional<bool> mSampleSize;
  bool mScrollWithPage;
  bool mViewportHeight;
  bool mViewportOffsetX;
  bool mViewportOffsetY;
  bool mViewportWidth;
  Optional<bool> mVolume;
  bool mWidth;

  MediaTrackSupportedConstraints();

  explicit inline MediaTrackSupportedConstraints(const FastDictionaryInitializer& )
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline MediaTrackSupportedConstraints(const MediaTrackSupportedConstraints& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const MediaTrackSupportedConstraints& aOther);

private:
  static bool
  InitIds(JSContext* cx, MediaTrackSupportedConstraintsAtoms* atomsCache);
};

namespace binding_detail {
struct FastMediaTrackSupportedConstraints : public MediaTrackSupportedConstraints
{
  inline FastMediaTrackSupportedConstraints()
    : MediaTrackSupportedConstraints(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_MediaTrackSupportedConstraintsBinding_h
