/* THIS FILE IS AUTOGENERATED FROM MmsMessage.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_MmsMessageBinding_h
#define mozilla_dom_MmsMessageBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct MmsDeliveryInfoAtoms;
class MmsMessage;
struct MmsMessageAtoms;
struct NativePropertyHooks;
class ProtoAndIfaceCache;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

struct MmsDeliveryInfo : public DictionaryBase
{
  nsString mDeliveryStatus;
  uint64_t mDeliveryTimestamp;
  nsString mReadStatus;
  uint64_t mReadTimestamp;
  nsString mReceiver;

  MmsDeliveryInfo();

  explicit inline MmsDeliveryInfo(const FastDictionaryInitializer& )
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline MmsDeliveryInfo(const MmsDeliveryInfo& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const MmsDeliveryInfo& aOther);

private:
  static bool
  InitIds(JSContext* cx, MmsDeliveryInfoAtoms* atomsCache);
};

namespace binding_detail {
struct FastMmsDeliveryInfo : public MmsDeliveryInfo
{
  inline FastMmsDeliveryInfo()
    : MmsDeliveryInfo(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


namespace MmsMessageBinding {

  typedef mozilla::dom::MmsMessage NativeType;

  // We declare this as an array so that retrieving a pointer to this
  // binding's property hooks only requires compile/link-time resolvable
  // address arithmetic.  Declaring it as a pointer instead would require
  // doing a run-time load to fetch a pointer to this binding's property
  // hooks.  And then structures which embedded a pointer to this structure
  // would require a run-time load for proper initialization, which would
  // then induce static constructors.  Lots of static constructors.
  extern const NativePropertyHooks sNativePropertyHooks[];

  JSObject*
  DefineDOMInterface(JSContext* aCx, JS::Handle<JSObject*> aGlobal, JS::Handle<jsid> id, bool aDefineOnGlobal);

  bool
  ConstructorEnabled(JSContext* aCx, JS::Handle<JSObject*> aObj);

  const JSClass*
  GetJSClass();

  bool
  Wrap(JSContext* aCx, mozilla::dom::MmsMessage* aObject, nsWrapperCache* aCache, JS::Handle<JSObject*> aGivenProto, JS::MutableHandle<JSObject*> aReflector);

  template <class T>
  inline JSObject* Wrap(JSContext* aCx, T* aObject, JS::Handle<JSObject*> aGivenProto)
  {
    JS::Rooted<JSObject*> reflector(aCx);
    return Wrap(aCx, aObject, aObject, aGivenProto, &reflector) ? reflector.get() : nullptr;
  }

  void
  ClearCachedDeliveryInfoValue(mozilla::dom::MmsMessage* aObject);

  void
  ClearCachedReceiversValue(mozilla::dom::MmsMessage* aObject);

  void
  ClearCachedAttachmentsValue(mozilla::dom::MmsMessage* aObject);

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx, JS::Handle<JSObject*> aGlobal);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, JS::Handle<JSObject*> aGlobal, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx, JS::Handle<JSObject*> aGlobal);

} // namespace MmsMessageBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_MmsMessageBinding_h
