/* THIS FILE IS AUTOGENERATED FROM Permissions.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_PermissionsBinding_h
#define mozilla_dom_PermissionsBinding_h

#include "PermissionsBinding.h"
#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
struct PermissionDescriptorAtoms;
class Permissions;
struct PermissionsAtoms;
class ProtoAndIfaceCache;
struct PushPermissionDescriptorAtoms;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

enum class PermissionName : uint32_t {
  Geolocation,
  Notifications,
  Push,
  EndGuard_
};

namespace PermissionNameValues {
extern const EnumEntry strings[4];
} // namespace PermissionNameValues

bool
ToJSValue(JSContext* aCx, PermissionName aArgument, JS::MutableHandle<JS::Value> aValue);


struct PermissionDescriptor : public DictionaryBase
{
  PermissionName mName;

  PermissionDescriptor();

  explicit inline PermissionDescriptor(const FastDictionaryInitializer& )
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline PermissionDescriptor(const PermissionDescriptor& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const PermissionDescriptor& aOther);

private:
  static bool
  InitIds(JSContext* cx, PermissionDescriptorAtoms* atomsCache);
};

namespace binding_detail {
struct FastPermissionDescriptor : public PermissionDescriptor
{
  inline FastPermissionDescriptor()
    : PermissionDescriptor(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


struct PushPermissionDescriptor : public PermissionDescriptor
{
  bool mUserVisible;

  PushPermissionDescriptor();

  explicit inline PushPermissionDescriptor(const FastDictionaryInitializer& )
    : PermissionDescriptor(FastDictionaryInitializer())
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline PushPermissionDescriptor(const PushPermissionDescriptor& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const PushPermissionDescriptor& aOther);

private:
  static bool
  InitIds(JSContext* cx, PushPermissionDescriptorAtoms* atomsCache);
};

namespace binding_detail {
struct FastPushPermissionDescriptor : public PushPermissionDescriptor
{
  inline FastPushPermissionDescriptor()
    : PushPermissionDescriptor(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


namespace PermissionsBinding {

  typedef mozilla::dom::Permissions NativeType;

  // We declare this as an array so that retrieving a pointer to this
  // binding's property hooks only requires compile/link-time resolvable
  // address arithmetic.  Declaring it as a pointer instead would require
  // doing a run-time load to fetch a pointer to this binding's property
  // hooks.  And then structures which embedded a pointer to this structure
  // would require a run-time load for proper initialization, which would
  // then induce static constructors.  Lots of static constructors.
  extern const NativePropertyHooks sNativePropertyHooks[];

  JSObject*
  DefineDOMInterface(JSContext* aCx, JS::Handle<JSObject*> aGlobal, JS::Handle<jsid> id, bool aDefineOnGlobal);

  const JSClass*
  GetJSClass();

  bool
  Wrap(JSContext* aCx, mozilla::dom::Permissions* aObject, nsWrapperCache* aCache, JS::Handle<JSObject*> aGivenProto, JS::MutableHandle<JSObject*> aReflector);

  template <class T>
  inline JSObject* Wrap(JSContext* aCx, T* aObject, JS::Handle<JSObject*> aGivenProto)
  {
    JS::Rooted<JSObject*> reflector(aCx);
    return Wrap(aCx, aObject, aObject, aGivenProto, &reflector) ? reflector.get() : nullptr;
  }

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx, JS::Handle<JSObject*> aGlobal);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, JS::Handle<JSObject*> aGlobal, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx, JS::Handle<JSObject*> aGlobal);

} // namespace PermissionsBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_PermissionsBinding_h
