/* THIS FILE IS AUTOGENERATED FROM SpeechSynthesisErrorEvent.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_SpeechSynthesisErrorEventBinding_h
#define mozilla_dom_SpeechSynthesisErrorEventBinding_h

#include "SpeechSynthesisEventBinding.h"
#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"
#include "mozilla/dom/SpeechSynthesisUtterance.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
class ProtoAndIfaceCache;
class SpeechSynthesisErrorEvent;
struct SpeechSynthesisErrorEventAtoms;
struct SpeechSynthesisErrorEventInitAtoms;
class SpeechSynthesisUtterance;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

enum class SpeechSynthesisErrorCode : uint32_t {
  Canceled,
  Interrupted,
  Audio_busy,
  Audio_hardware,
  Network,
  Synthesis_unavailable,
  Synthesis_failed,
  Language_unavailable,
  Voice_unavailable,
  Text_too_long,
  Invalid_argument,
  EndGuard_
};

namespace SpeechSynthesisErrorCodeValues {
extern const EnumEntry strings[12];
} // namespace SpeechSynthesisErrorCodeValues

bool
ToJSValue(JSContext* aCx, SpeechSynthesisErrorCode aArgument, JS::MutableHandle<JS::Value> aValue);


struct SpeechSynthesisErrorEventInit : public SpeechSynthesisEventInit
{
  SpeechSynthesisErrorCode mError;

  SpeechSynthesisErrorEventInit();

  explicit inline SpeechSynthesisErrorEventInit(const FastDictionaryInitializer& )
    : SpeechSynthesisEventInit(FastDictionaryInitializer())
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline SpeechSynthesisErrorEventInit(const SpeechSynthesisErrorEventInit& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const SpeechSynthesisErrorEventInit& aOther);

private:
  static bool
  InitIds(JSContext* cx, SpeechSynthesisErrorEventInitAtoms* atomsCache);
};

namespace binding_detail {
struct FastSpeechSynthesisErrorEventInit : public SpeechSynthesisErrorEventInit
{
  inline FastSpeechSynthesisErrorEventInit()
    : SpeechSynthesisErrorEventInit(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


namespace SpeechSynthesisErrorEventBinding {

  typedef mozilla::dom::SpeechSynthesisErrorEvent NativeType;

  // We declare this as an array so that retrieving a pointer to this
  // binding's property hooks only requires compile/link-time resolvable
  // address arithmetic.  Declaring it as a pointer instead would require
  // doing a run-time load to fetch a pointer to this binding's property
  // hooks.  And then structures which embedded a pointer to this structure
  // would require a run-time load for proper initialization, which would
  // then induce static constructors.  Lots of static constructors.
  extern const NativePropertyHooks sNativePropertyHooks[];

  JSObject*
  DefineDOMInterface(JSContext* aCx, JS::Handle<JSObject*> aGlobal, JS::Handle<jsid> id, bool aDefineOnGlobal);

  bool
  ConstructorEnabled(JSContext* aCx, JS::Handle<JSObject*> aObj);

  const JSClass*
  GetJSClass();

  bool
  Wrap(JSContext* aCx, mozilla::dom::SpeechSynthesisErrorEvent* aObject, nsWrapperCache* aCache, JS::Handle<JSObject*> aGivenProto, JS::MutableHandle<JSObject*> aReflector);

  template <class T>
  inline JSObject* Wrap(JSContext* aCx, T* aObject, JS::Handle<JSObject*> aGivenProto)
  {
    JS::Rooted<JSObject*> reflector(aCx);
    return Wrap(aCx, aObject, aObject, aGivenProto, &reflector) ? reflector.get() : nullptr;
  }

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx, JS::Handle<JSObject*> aGlobal);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, JS::Handle<JSObject*> aGlobal, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx, JS::Handle<JSObject*> aGlobal);

} // namespace SpeechSynthesisErrorEventBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_SpeechSynthesisErrorEventBinding_h
