/* THIS FILE IS AUTOGENERATED FROM WidevineCDMManifest.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_WidevineCDMManifestBinding_h
#define mozilla_dom_WidevineCDMManifestBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
class ProtoAndIfaceCache;
struct WidevineCDMManifestAtoms;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

struct WidevineCDMManifest : public DictionaryBase
{
  nsString mDescription;
  nsString mName;
  nsString mVersion;
  nsString mX_cdm_codecs;
  nsString mX_cdm_host_versions;
  nsString mX_cdm_interface_versions;
  nsString mX_cdm_module_versions;

  WidevineCDMManifest();

  explicit inline WidevineCDMManifest(const FastDictionaryInitializer& )
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline WidevineCDMManifest(const WidevineCDMManifest& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const WidevineCDMManifest& aOther);

private:
  static bool
  InitIds(JSContext* cx, WidevineCDMManifestAtoms* atomsCache);
};

namespace binding_detail {
struct FastWidevineCDMManifest : public WidevineCDMManifest
{
  inline FastWidevineCDMManifest()
    : WidevineCDMManifest(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_WidevineCDMManifestBinding_h
